name: ember_trip
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: any
  provider: ^6.1.2
  mapbox_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.8
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
